BEGIN;

CREATE TABLE IF NOT EXISTS faculty_subject_assignments (
    assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_sr_no INTEGER NOT NULL REFERENCES faculties(sr_no) ON DELETE CASCADE,
    subjectcode VARCHAR(40) NOT NULL REFERENCES subject(subjectcode) ON DELETE RESTRICT,
    courcecode VARCHAR(20) NOT NULL,
    semoryear INTEGER NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT faculty_subject_assignments_unique
        UNIQUE (faculty_sr_no, subjectcode, courcecode, semoryear)
);

      -- The application accesses this table through the backend's PostgreSQL connection.
      -- No public client policy is required; RLS blocks anon/authenticated API access.
      ALTER TABLE faculty_subject_assignments ENABLE ROW LEVEL SECURITY;

-- Preserve assignments that were stored in the old one-subject faculty columns.
INSERT INTO faculty_subject_assignments
    (faculty_sr_no, subjectcode, courcecode, semoryear)
SELECT sr_no, subject, courcecode, semoryear
FROM faculties
WHERE subject IS NOT NULL
  AND subject <> ''
  AND subject <> 'NOT ASSIGNED'
  AND courcecode IS NOT NULL
  AND courcecode <> 'NOT ASSIGNED'
  AND semoryear <> 0
ON CONFLICT (faculty_sr_no, subjectcode, courcecode, semoryear) DO NOTHING;

COMMIT;
