BEGIN;

-- Fee assignment for one student in one course term.
CREATE TABLE IF NOT EXISTS fee_accounts (
    fee_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(sr_no) ON DELETE CASCADE,
    course_code VARCHAR(20) NOT NULL,
    semoryear INTEGER NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fee_accounts_student_term_unique UNIQUE (student_id, course_code, semoryear),
    CONSTRAINT fee_accounts_course_term_check CHECK (course_code <> '' AND semoryear > 0)
);

-- Payment ledger. Each payment keeps its amount and date instead of replacing history.
CREATE TABLE IF NOT EXISTS fee_payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_account_id BIGINT NOT NULL REFERENCES fee_accounts(fee_account_id) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_by VARCHAR(255),
    note VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS fee_accounts_class_idx
    ON fee_accounts(course_code, semoryear);

CREATE INDEX IF NOT EXISTS fee_payments_account_idx
    ON fee_payments(fee_account_id, paid_at DESC);

CREATE OR REPLACE FUNCTION update_fee_accounts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS fee_accounts_updated_at_trigger ON fee_accounts;
CREATE TRIGGER fee_accounts_updated_at_trigger
    BEFORE UPDATE ON fee_accounts
    FOR EACH ROW
    EXECUTE FUNCTION update_fee_accounts_updated_at();

COMMIT;
