BEGIN;

-- Student-submitted claims for payments made through the official UPI destination.
CREATE TABLE IF NOT EXISTS fee_payment_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_account_id BIGINT NOT NULL REFERENCES fee_accounts(fee_account_id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES students(sr_no) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL,
    utr VARCHAR(100) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at TIMESTAMP,
    rejected_at TIMESTAMP,
    verified_by VARCHAR(255) REFERENCES admin(emailid) ON DELETE RESTRICT,
    rejected_by VARCHAR(255) REFERENCES admin(emailid) ON DELETE RESTRICT,
    rejection_reason_code VARCHAR(50),
    rejection_reason_text VARCHAR(500),

    CONSTRAINT fee_payment_requests_amount_check
        CHECK (amount > 0 AND amount = trunc(amount) AND mod(amount, 100) = 0),
    CONSTRAINT fee_payment_requests_utr_check
        CHECK (btrim(utr) <> ''),
    CONSTRAINT fee_payment_requests_status_check
        CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT fee_payment_requests_pending_metadata_check
        CHECK (
            status <> 'PENDING'
            OR (
                verified_at IS NULL
                AND verified_by IS NULL
                AND rejected_at IS NULL
                AND rejected_by IS NULL
                AND rejection_reason_code IS NULL
                AND rejection_reason_text IS NULL
            )
        ),
    CONSTRAINT fee_payment_requests_verification_check
        CHECK (
            status <> 'VERIFIED'
            OR (
                verified_at IS NOT NULL
                AND verified_by IS NOT NULL
                AND rejected_at IS NULL
                AND rejected_by IS NULL
                AND rejection_reason_code IS NULL
                AND rejection_reason_text IS NULL
            )
        ),
    CONSTRAINT fee_payment_requests_rejection_audit_check
        CHECK (
            status <> 'REJECTED'
            OR (
                verified_at IS NULL
                AND verified_by IS NULL
                AND rejected_at IS NOT NULL
                AND rejected_by IS NOT NULL
                AND (
                    NULLIF(btrim(COALESCE(rejection_reason_code, '')), '') IS NOT NULL
                    OR NULLIF(btrim(COALESCE(rejection_reason_text, '')), '') IS NOT NULL
                )
            )
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS fee_payment_requests_utr_uidx
    ON fee_payment_requests(btrim(utr));

CREATE INDEX IF NOT EXISTS fee_payment_requests_status_idx
    ON fee_payment_requests(status);

CREATE INDEX IF NOT EXISTS fee_payment_requests_student_idx
    ON fee_payment_requests(student_id);

CREATE INDEX IF NOT EXISTS fee_payment_requests_account_idx
    ON fee_payment_requests(fee_account_id);

-- A submitted request is immutable with respect to its terminal status.
CREATE OR REPLACE FUNCTION prevent_fee_payment_request_status_regression()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'PENDING' THEN
            RAISE EXCEPTION 'New fee payment requests must start as pending';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.status <> 'PENDING' THEN
        IF NEW.status IS DISTINCT FROM OLD.status
           OR NEW.amount IS DISTINCT FROM OLD.amount
           OR NEW.utr IS DISTINCT FROM OLD.utr
           OR NEW.student_id IS DISTINCT FROM OLD.student_id
           OR NEW.fee_account_id IS DISTINCT FROM OLD.fee_account_id
           OR NEW.submitted_at IS DISTINCT FROM OLD.submitted_at
           OR NEW.verified_at IS DISTINCT FROM OLD.verified_at
           OR NEW.verified_by IS DISTINCT FROM OLD.verified_by
           OR NEW.rejected_at IS DISTINCT FROM OLD.rejected_at
           OR NEW.rejected_by IS DISTINCT FROM OLD.rejected_by
           OR NEW.rejection_reason_code IS DISTINCT FROM OLD.rejection_reason_code
           OR NEW.rejection_reason_text IS DISTINCT FROM OLD.rejection_reason_text THEN
            RAISE EXCEPTION 'Terminal fee payment requests are immutable';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS fee_payment_requests_status_transition_trigger
    ON fee_payment_requests;
CREATE TRIGGER fee_payment_requests_status_transition_trigger
    BEFORE INSERT OR UPDATE ON fee_payment_requests
    FOR EACH ROW
    EXECUTE FUNCTION prevent_fee_payment_request_status_regression();

-- Extend the existing unified ledger. Existing rows are manual payments.
ALTER TABLE fee_payments
    ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN IF NOT EXISTS payment_request_id BIGINT,
    ADD COLUMN IF NOT EXISTS fee_applied_amount NUMERIC(12, 2),
    ADD COLUMN IF NOT EXISTS credit_amount NUMERIC(12, 2);

UPDATE fee_payments
SET fee_applied_amount = amount,
    credit_amount = 0
WHERE fee_applied_amount IS NULL
   OR credit_amount IS NULL;

ALTER TABLE fee_payments
    ALTER COLUMN fee_applied_amount DROP DEFAULT,
    ALTER COLUMN credit_amount DROP DEFAULT;

CREATE OR REPLACE FUNCTION normalize_fee_payment_breakdown()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.source = 'MANUAL'
       AND NEW.payment_request_id IS NULL
       AND NEW.fee_applied_amount IS NULL
       AND NEW.credit_amount IS NULL THEN
        NEW.fee_applied_amount = NEW.amount;
        NEW.credit_amount = 0;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS fee_payments_breakdown_trigger ON fee_payments;
CREATE TRIGGER fee_payments_breakdown_trigger
    BEFORE INSERT OR UPDATE ON fee_payments
    FOR EACH ROW
    EXECUTE FUNCTION normalize_fee_payment_breakdown();

ALTER TABLE fee_payments
    ADD CONSTRAINT fee_payments_source_check
        CHECK (source IN ('UPI_REQUEST', 'MANUAL')),
    ADD CONSTRAINT fee_payments_amount_breakdown_check
        CHECK (
            amount = fee_applied_amount + credit_amount
            AND fee_applied_amount IS NOT NULL
            AND credit_amount IS NOT NULL
            AND fee_applied_amount >= 0
            AND credit_amount >= 0
        ),
    ADD CONSTRAINT fee_payments_source_request_check
        CHECK (
            (source = 'UPI_REQUEST' AND payment_request_id IS NOT NULL)
            OR (source = 'MANUAL' AND payment_request_id IS NULL)
        );

ALTER TABLE fee_payments
    ADD CONSTRAINT fee_payments_payment_request_fk
        FOREIGN KEY (payment_request_id)
        REFERENCES fee_payment_requests(request_id)
        ON DELETE RESTRICT;

CREATE UNIQUE INDEX IF NOT EXISTS fee_payments_payment_request_uidx
    ON fee_payments(payment_request_id)
    WHERE payment_request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS fee_payments_source_idx
    ON fee_payments(source);

-- Reusable student-level credit produced by verified overpayments.
CREATE TABLE IF NOT EXISTS fee_credit_ledger (
    ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(sr_no) ON DELETE RESTRICT,
    entry_type VARCHAR(20) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    fee_payment_id BIGINT REFERENCES fee_payments(payment_id) ON DELETE RESTRICT,
    fee_account_id BIGINT REFERENCES fee_accounts(fee_account_id) ON DELETE RESTRICT,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fee_credit_ledger_entry_type_check
        CHECK (entry_type IN ('CREDIT_CREATED', 'CREDIT_APPLIED')),
    CONSTRAINT fee_credit_ledger_reference_check
        CHECK (
            (entry_type = 'CREDIT_CREATED' AND fee_payment_id IS NOT NULL)
            OR (entry_type = 'CREDIT_APPLIED' AND fee_account_id IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS fee_credit_ledger_student_idx
    ON fee_credit_ledger(student_id, created_at DESC);

CREATE INDEX IF NOT EXISTS fee_credit_ledger_payment_idx
    ON fee_credit_ledger(fee_payment_id);

CREATE INDEX IF NOT EXISTS fee_credit_ledger_account_idx
    ON fee_credit_ledger(fee_account_id);

-- One current payment destination is shared by every term of a course.
CREATE TABLE IF NOT EXISTS fee_course_payment_methods (
    payment_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(20) NOT NULL REFERENCES courses(course_code) ON DELETE CASCADE,
    upi_id VARCHAR(255) NOT NULL,
    qr_storage_path TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fee_course_payment_methods_course_unique UNIQUE (course_code),
    CONSTRAINT fee_course_payment_methods_upi_check CHECK (btrim(upi_id) <> ''),
    CONSTRAINT fee_course_payment_methods_qr_path_check CHECK (btrim(qr_storage_path) <> '')
);

CREATE INDEX IF NOT EXISTS fee_course_payment_methods_course_idx
    ON fee_course_payment_methods(course_code);

CREATE OR REPLACE FUNCTION update_fee_course_payment_methods_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS fee_course_payment_methods_updated_at_trigger
    ON fee_course_payment_methods;
CREATE TRIGGER fee_course_payment_methods_updated_at_trigger
    BEFORE UPDATE ON fee_course_payment_methods
    FOR EACH ROW
    EXECUTE FUNCTION update_fee_course_payment_methods_updated_at();

-- Audit changes to an already-created fee account.
CREATE TABLE IF NOT EXISTS fee_adjustments (
    adjustment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_account_id BIGINT NOT NULL REFERENCES fee_accounts(fee_account_id) ON DELETE RESTRICT,
    previous_total NUMERIC(12, 2) NOT NULL CHECK (previous_total >= 0),
    new_total NUMERIC(12, 2) NOT NULL CHECK (new_total >= 0),
    delta NUMERIC(12, 2) GENERATED ALWAYS AS (new_total - previous_total) STORED,
    reason VARCHAR(255) NOT NULL,
    adjusted_by VARCHAR(255) NOT NULL REFERENCES admin(emailid) ON DELETE RESTRICT,
    adjusted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS fee_adjustments_account_idx
    ON fee_adjustments(fee_account_id, adjusted_at DESC);

COMMIT;